/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { GlucoseListRelationFilter } from "../../glucose/base/GlucoseListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { InsulinListRelationFilter } from "../../insulin/base/InsulinListRelationFilter";
import { MealListRelationFilter } from "../../meal/base/MealListRelationFilter";
import { SleepListRelationFilter } from "../../sleep/base/SleepListRelationFilter";

@InputType()
class UserWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  firstName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => GlucoseListRelationFilter,
  })
  @ValidateNested()
  @Type(() => GlucoseListRelationFilter)
  @IsOptional()
  @Field(() => GlucoseListRelationFilter, {
    nullable: true,
  })
  glucose?: GlucoseListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => InsulinListRelationFilter,
  })
  @ValidateNested()
  @Type(() => InsulinListRelationFilter)
  @IsOptional()
  @Field(() => InsulinListRelationFilter, {
    nullable: true,
  })
  insulin?: InsulinListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  lastName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => MealListRelationFilter,
  })
  @ValidateNested()
  @Type(() => MealListRelationFilter)
  @IsOptional()
  @Field(() => MealListRelationFilter, {
    nullable: true,
  })
  meals?: MealListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => SleepListRelationFilter,
  })
  @ValidateNested()
  @Type(() => SleepListRelationFilter)
  @IsOptional()
  @Field(() => SleepListRelationFilter, {
    nullable: true,
  })
  sleep?: SleepListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  username?: StringFilter;
}

export { UserWhereInput as UserWhereInput };
