/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { GlucoseCreateNestedManyWithoutUsersInput } from "./GlucoseCreateNestedManyWithoutUsersInput";
import { Type } from "class-transformer";
import { InsulinCreateNestedManyWithoutUsersInput } from "./InsulinCreateNestedManyWithoutUsersInput";
import { MealCreateNestedManyWithoutUsersInput } from "./MealCreateNestedManyWithoutUsersInput";
import { IsJSONValue } from "@app/custom-validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { SleepCreateNestedManyWithoutUsersInput } from "./SleepCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: () => GlucoseCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => GlucoseCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => GlucoseCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  glucose?: GlucoseCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => InsulinCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => InsulinCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => InsulinCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  insulin?: InsulinCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: () => MealCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => MealCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => MealCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  meals?: MealCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => SleepCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SleepCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SleepCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  sleep?: SleepCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;
}

export { UserCreateInput as UserCreateInput };
